services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: back
    image: orion-microcrm-back:local
    ports:
      - "8080:8080"
    networks:
      - microcrm

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: front
    image: orion-microcrm-front:local
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - microcrm

  monitoring:
    profiles:
      - monitoring
    build:
      context: .
      dockerfile: Dockerfile
      target: standalone
    image: orion-microcrm-standalone:local
    ports:
      - "8443:443"
      - "8080:8080"
    networks:
      - microcrm

networks:
  microcrm:
    driver: bridge
